name: Automated Review
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          fetch-depth: 0

      - name: Fetch Diff
        run: git diff origin/${{ github.base_ref }} origin/${{ github.head_ref }} > diff.txt

      - name: Write Comment
        run: gh pr review ${{ github.event.number }} --body "$(cat diff.txt)" --comment
        with:
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}