name: Automated Review
on: 
  issue_comment:
    types: [created]

jobs:
  review:
    if: github.event.issue.pull_request
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          fetch-depth: 0

      - uses: actions/setup-go@v2
        with:
          go-version: 1.22

      - name: Fetch Diff
        run: git diff origin/${{ github.base_ref }} origin/${{ github.head_ref }} > diff.txt

      - name: Request to GPT
        run: go run gpt_client.go
        env:
          API_KEY: ${{ secrets.API_KEY }}

      - name: Write Comment
        run: gh pr review ${{ github.event.number }} --body "$(cat message.txt)" --comment
        env:
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}