name: Automated Review
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Run review
        run: |
          echo "Reviewing PR"
          echo "Review complete"