name: Automated Review
on: 
  issue_comment:
    types: [created]

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          fetch-depth: 0

      - uses: actions/setup-go@v2
        with:
          go-version: 1.22

      - name: Fetch Diff
        run: |
          BASE_REF=$(jq --raw-output .pull_request.base.ref $GITHUB_EVENT_PATH)
          HEAD_REF=$(jq --raw-output .pull_request.head.ref $GITHUB_EVENT_PATH)
          git diff origin/$BASE_REF origin/$HEAD_REF > diff.txt
        env:
          GITHUB_EVENT_PATH: ${{ github.event_path }}

      - name: Request to GPT
        #run: go run gpt_client.go
        run: echo "Sample Message" > message.txt
        env:
          API_KEY: ${{ secrets.API_KEY }}

      - name: Write Comment
        run: gh pr review ${{ github.event.pull_request.number }} --body "$(cat message.txt)" --comment
        env:
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}